name = "Taxonomy"
uuid = "fea09e6a-dc4a-42ec-a35f-5cfade855812"
authors = ["Aaron Peikert", "Maximilian S. Ernst", "Clifford Bode", "Nicklas Hafiz"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
StenoGraphs = "78862bba-adae-4a83-bb4d-33c106177f81"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
HTTP = "0.9, 1"
JSON = "0.21"
StenoGraphs = "0.2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
